"""Regenerate LEADERBOARD.md from testing/bench/results/*/metrics.json."""
from __future__ import annotations
from pathlib import Path
import json
import math


def regenerate_leaderboard(results_dir: Path, md_path: Path) -> None:
    rows: list[dict] = []
    for version_dir in sorted(results_dir.iterdir()):
        if not version_dir.is_dir():
            continue
        m = version_dir / "metrics.json"
        p = version_dir / "params.json"
        if not m.exists() or not p.exists():
            continue
        metrics = json.loads(m.read_text()).get("val", {})
        params = json.loads(p.read_text())
        spearman = metrics.get("spearman", float("nan"))
        # Skip rows with NaN spearman — unstable sort, meaningless rank
        if math.isnan(spearman):
            continue
        rows.append({
            "version": version_dir.name,
            "date": params.get("date", ""),
            "spearman": spearman,
            "mae": metrics.get("mae", float("nan")),
            "off_by_one": metrics.get("off_by_one", float("nan")),
            "ensemble": "+".join(params.get("ensemble", [])),
            "notes": params.get("notes", ""),
        })

    rows.sort(key=lambda r: -r["spearman"])

    lines = [
        "# Rating Ensemble Leaderboard",
        "",
        "Sorted by val Spearman (desc). Regenerated by `run.py leaderboard`.",
        "",
        "| Version | Date | Spearman | MAE | ±1 acc | Ensemble | Notes |",
        "|---|---|---|---|---|---|---|",
    ]
    for r in rows:
        mae = r["mae"]
        off_by_one = r["off_by_one"]
        mae_str = f"{mae:.2f}" if not math.isnan(mae) else "n/a"
        obo_str = f"{off_by_one*100:.0f}%" if not math.isnan(off_by_one) else "n/a"
        lines.append(
            f"| {r['version']} | {r['date']} | {r['spearman']:.3f} | {mae_str} | "
            f"{obo_str} | {r['ensemble']} | {r['notes']} |"
        )
    md_path.write_text("\n".join(lines) + "\n")
